"""Ready-to-adapt end-user notice text for the disclosure INSAIT's ToS requires.

`bggpt.ai/terms` Art. 5.8(2) requires explicitly notifying end users that a product is based on
the BgGPT Model — see `identity_guard.py`'s module docstring and the README's licensing note for
the full citation. That's a *product*-level notice obligation: it needs to live somewhere an end
user can actually see it (a footer, an about page, a rights/ToS section), not just be answerable
if someone happens to ask the chatbot directly.

`render()` returns a paragraph of plain text you can drop into such a page. It's modeled on a real
notice already shipped in production for another BgGPT-based product, genericized with your
product's name. Adapt the wording to fit your product and language conventions — this is a
starting point, not legal advice; read `bggpt.ai/terms` and `ai.google.dev/gemma/terms` yourself
if this matters for your use case.
"""

from __future__ import annotations

INSAIT_URL = "https://insait.ai/"
BGGPT_TERMS_URL = "https://bggpt.ai/terms"
GEMMA_TERMS_URL = "https://ai.google.dev/gemma/terms"
GEMMA_PROHIBITED_USE_URL = "https://ai.google.dev/gemma/prohibited_use_policy"

_TEMPLATE_BG = (
    "Отговорите в {product_name} се генерират от BgGPT — езиков модел на INSAIT ({insait_url}). "
    "Достъпът до BgGPT е съгласно Общите условия на INSAIT ({bggpt_terms_url}). BgGPT е "
    "производен на Google Gemma и се предоставя съгласно Gemma Terms of Use ({gemma_terms_url}); "
    "използването на {product_name} е предмет на тези условия и на Gemma Prohibited Use Policy "
    "({gemma_prohibited_url})."
)

_TEMPLATE_EN = (
    "Answers in {product_name} are generated by BgGPT — a language model by INSAIT "
    "({insait_url}). Access to BgGPT is provided under INSAIT's Terms of Service "
    "({bggpt_terms_url}). BgGPT is derived from Google Gemma and is provided under the Gemma "
    "Terms of Use ({gemma_terms_url}); use of {product_name} is subject to those terms and to "
    "the Gemma Prohibited Use Policy ({gemma_prohibited_url})."
)

_TEMPLATES = {"bg": _TEMPLATE_BG, "en": _TEMPLATE_EN}


def render(product_name: str, lang: str = "bg") -> str:
    """Return a plain-text end-user notice disclosing that `product_name` is BgGPT-based.

    Args:
        product_name: your product's name, inserted into the notice text.
        lang: "bg" (default) or "en".

    Raises:
        ValueError: if `lang` isn't "bg" or "en".
    """
    template = _TEMPLATES.get(lang)
    if template is None:
        raise ValueError(f"Unsupported lang {lang!r}; use 'bg' or 'en'.")
    return template.format(
        product_name=product_name,
        insait_url=INSAIT_URL,
        bggpt_terms_url=BGGPT_TERMS_URL,
        gemma_terms_url=GEMMA_TERMS_URL,
        gemma_prohibited_url=GEMMA_PROHIBITED_USE_URL,
    )
